### ISSUE TITLE
App doesn't load all content 

### ISSUE THREAD

**Issue by Arjanvde** [4np/TVGemist#6] opened 2018-03-26 19:07 UTC
## Short description of the issue

Installed the new version of the app today, unfortunately the app doesn't load any "new" content.
The filers are set to "alle genres" but no content is displayd at the letter "a" or " yesterday" 

The log says:
[ProgramsDetailViewController.swift:84] setupPaginator() > Could not fetch filtered programs (De gegevens kunnen niet worden gelezen omdat ze ontbreken.)

Any troubleshoot help?

## Issue type

Bug

**Comment by 4np** [comment] 2018-03-27 07:38
Sounds like a duplicate of #4. I can reproduce the issue for all the letter filters. The NPO has also changed the filter order from `Meest bekeken` > `Genre` > `A-Z` to `A-Z` > `Genre` > `Meest bekeken` which probably works well on web, but doesn't work so well on TV.

**Comment by 4np** [comment] 2018-03-27 08:47
I can reproduce the issue for all the letter filters. The NPO has also changed the filter order from `Meest bekeken` > `Genre` > `A-Z` to `A-Z` > `Genre` > `Meest bekeken` which probably works well on web, but doesn't work so well on TV.

**Closed as completed** 2018-03-27 10:37 UTC
Labels: bug

**Comment by 4np** [comment] 2018-03-27 10:39
The issue is fixed in `master` branch, but I have not yet released the new version as it requires `Xcode 9.3` / `Swift 4.1`. Both are _expected_ to launch today after the [Apple Education Event](https://www.theverge.com/2018/3/22/17147910/apple-event-time-education-ipad-macbook-pencil-what-to-expect).

**Comment by Arjanvde** [comment] 2018-03-27 19:38
Thanks for the trouble shooting, works like a charm again!!

**Comment by 4np** [comment] 2018-03-30 07:23
Xcode 9.3 was just released so I'll be tagging a new release shortly...

<img width="1181" alt="screen shot 2018-03-30 at 09 20 32" src="https://user-images.githubusercontent.com/1049693/38128696-f5b858a8-33fb-11e8-80af-3384d1789878.png">
